### ISSUE TITLE
Reconsider bug fixing description

### ISSUE THREAD

**Issue by terrarier2111** [taiki-e/portable-atomic#153] opened 2024-03-08 21:45 UTC
In the description of this crate there is a mention of bugs in std being avoided by using this crate but after the news in https://github.com/rust-lang/rust/issues/100650 the validity of this statement should be reconsidered

**Comment by taiki-e** [comment] 2024-03-09 02:55
I believe the MIPS one is fixed in LLVM, but the fix should not yet be available in rustc. The arm one is not yet fixed as far as I know (LLVM isssue is still open). The powerpc one is supposedly fixed in LLVM, but when I tested it before with the version that was supposed to contain the fix, the problem was not actually fixed. (I'm aware of other bugs besides this regarding powerpc, and I should minimize and report them, but enough minimizing the repro is not easy...)

This problem is already tracked in #2, where there is a description of the conditions under which the problem occurs, but note that this is a bug that can be hidden by other factors, especially the presence or absence of optimization, since it is UB. So random "I can't reproduce this" comments are not necessarily reliable.

Eventually, when all of these are fixed, I would close #2 and change the description to something like "LLVM bugs affecting rustc 1.N and earlier", but at least that is not something that can be done right now.

I'm going to close this in favor of a #2 that tracks the problem more exhaustively.

**Closed by taiki-e** 2024-03-09 02:55 UTC
Labels: C-question

**Comment by taiki-e** [comment] 2024-04-11 14:12
The MIPS issue also does not appear to be actually fixed. https://github.com/rust-lang/rust/issues/123772
